stages:
  - build
  - deploy

build_image:
  stage: build
  only: [master]
  image: kovaron/angular2-sb-builder
  script:
    - cd frontend
    - npm install
    - ng build --prod
    - cd ..
    - cd backend
    - for f in src/main/resources/static/*.js; do gzip -9 < $f > $f.gz; done
    - mvn clean install -DskipTests
    - mv target/backend-0.0.1-SNAPSHOT.jar ../admin.jar
  artifacts:
    paths:
      - admin.jar

deploy_image:
  stage: deploy
  only: [master]
  image: ekino/docker-buildbox:latest-dind-aws
  services:
    - docker:dind
  script:
    - eval $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t app-system-admin .
    - docker tag app-system-admin:latest 807560053962.dkr.ecr.eu-central-1.amazonaws.com/app-system-admin:latest
    - docker push 807560053962.dkr.ecr.eu-central-1.amazonaws.com/app-system-admin:latest